Quiz card compontent & page
czintel/capstone-project pull request #15
Opened 2021-06-17 22:22 UTC by czintel

- Card input is pulled from data.json
- The correct answer of the first card is the first answer, the correct answer of the second card is the second one, and so on

2021-06-17 22:31 UTC, hugh-burgess commented
The more commits the better!

2021-06-18 06:40 UTC, macfrei requested changes
Nice job! I added a few comments! This PullRequest also got really big, please try to create smaller ones in the future. Keep it up! 🚀

2021-06-18 06:40 UTC, macfrei commented on src/App.js
> +// }
Please remove unused code. Implementing the router should probably be a different task and a different PR.

2021-06-18 06:40 UTC, macfrei commented on src/components/Button.js
> +  width: 100px;
Hm, what about if you have longer text in the button? I wouldn't set a fixed width on this component. How about `min-content`? Then it is always just as big as the text inside. And if you want to overwrite it, you can do so in the component where you use it.

2021-06-18 06:40 UTC, macfrei commented on src/components/Button.js
> +  font-size: 15px;
You set the default `font-size` to 112.5%. If you now set a size with `px` here, this font won't be responsive if someone who needs it is zooming in. Have a look into  the `rem` unit which is relative to the root font-size.

2021-06-18 06:40 UTC, macfrei commented on src/components/ButtonExpansion.js
> +  font-size: 20px;
Same here as above. Have a look into `rem`

2021-06-18 06:40 UTC, macfrei commented on src/components/ButtonExpansion.spec.js
> +  it('contains a text', async () => {
```suggestion
  it('contains a text', () => {
```

2021-06-18 06:40 UTC, macfrei commented on src/components/Button.js
> +export default function Button({ onClick, children, ...props }) {
No test and story for this component?

2021-06-18 06:40 UTC, macfrei commented on src/components/LearningCard.js
> +      <GlobalStyle />
....... I think we have talked about this? 😸

2021-06-18 06:40 UTC, macfrei commented on src/components/LearningCard.js
> +        <h2 isExpanded={isExpanded}>{name}</h2>
This doesn't do anything here as a normal `h2` is not a styled-component. The reason it works is because of giving the props to `LearningCard`.
```suggestion
        <h2>{name}</h2>
```

2021-06-18 06:40 UTC, macfrei commented on src/components/LearningCard.js
> +  color: PropTypes.string,
The props for your card do not include `onClick` and `isExpanded`.
```suggestion
  name: PropTypes.string,
  description: PropTypes.string,
  tags: PropTypes.array,
  color: PropTypes.string,
```

2021-06-18 06:40 UTC, macfrei commented on src/components/LearningCard.js
> +const LearningCard = styled.div`
I think this would be a `section`.
```suggestion
const LearningCard = styled.section`
```

2021-06-18 06:40 UTC, macfrei commented on src/components/LearningCard.js
> +    font-size: ${prop => (prop.isExpanded ? '50px' : '30px')};
Please no fixed font-sizes. Not going to add another comment about this, but please go over _all_ your components and check out `rem` 🙂

2021-06-18 06:40 UTC, macfrei commented on src/components/LearningCard.spec.js
> +    ).toBeInTheDocument()
I think it would be better to have each of these in one test. Also, this should fail as `tags` is an array and not a string.

2021-06-18 06:40 UTC, macfrei commented on src/components/LearningCard.spec.js
> +        tags="Tag of the emotion"
```suggestion
        tags=["Fear", "Joy"]
```

2021-06-18 06:40 UTC, macfrei commented on src/components/QuizCard.js
> +  isClicked: PropTypes.bool,
Again here, the only props your `QuizCard` gets are `title`, `scenario`, `question` and `answers`.

2021-06-18 06:40 UTC, macfrei commented on src/components/QuizCard.js
> +const Card = styled.div`
```suggestion
const Card = styled.section`
```

2021-06-18 06:40 UTC, macfrei commented on src/components/QuizCard.js
> +  }
Like this solution!

2021-06-18 06:40 UTC, macfrei commented on src/pages/LearningCardPage.spec.js
> +})
Looks like you forgot this test!

2021-06-18 06:40 UTC, macfrei commented on src/pages/QuizCardPage.js
> +          // }
Please remove commented out code!

2021-06-18 06:40 UTC, macfrei commented on src/pages/QuizCardPage.js
> +          key={index}
Please don't use the `index` as key.

2021-06-18 06:40 UTC, macfrei commented on src/pages/QuizCardPage.js
> +          isCorrect={answers.isCorrect}
This is kind of unnecessary as you are giving the `answers` directly. Also, are you even receiving them in your `QuizCard` component as props? I think these can be removed.

2021-06-18 09:03 UTC, czintel commented on src/components/QuizCard.js
> +  }
Thank you :-)

2021-06-18 09:06 UTC, czintel commented on src/pages/QuizCardPage.js
> +          isCorrect={answers.isCorrect}
True, I removed them!

2021-06-18 09:10 UTC, czintel commented on src/pages/QuizCardPage.js
> +          key={index}
I added "qId" to my data.json question entries and use them as keys now. thanks for the suggestion :-)

2021-06-18 09:56 UTC, merged